### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Mohiis** [nguyen-group/QERaman#2]
Hi,

I tried to install the code but following error appeared on Ubuntu with ifort compiler. MacOS and MInt with gcc checked as well but same error happened.

`phq_readin2.f90(73): error #6580: Name in only-list does not exist or is not accessible.   [HUBBARD_PROJECTORS]
  USE ldaU,          ONLY : lda_plus_u, Hubbard_projectors, lda_plus_u_kind
----------------------------------------^
phq_readin2.f90(790): error #6404: This name does not have a type, and must have an explicit type.   [HUBBARD_PROJECTORS]
     IF (Hubbard_projectors.NE."atomic") CALL errore("phq_readin", &
---------^
compilation aborted for phq_readin2.f90 (code 1)
make: *** [../../make.inc:16: phq_readin2.o] Error 1
`

**Comment by nguyen-group** [comment]
Hi, this error occurred at line 73 of phq_readin2.f90. This line is the same as QE's original file phq_readin.f90 (https://gitlab.com/QEF/q-e/blob/develop/PHonon/PH/phq_readin.f90). Did you finish installing ph.x in QE by "make pw pp ph" or "make all" before installing QERaman?

**Comment by Mohiis** [comment]
Hi, Yes, QE is compiled and works well. I also tried to compile a fresh version of QE using "make pw pp ph" or "make all" but the same issue was raised.

**Comment by nguyen-group** [comment]
I tried with ifort compiler with both QE 7.1 and 7.2. It can pass the phq_readin2.f90 well. Which version of QE are you using?
I suggest using the newest ones, QE 7.1 or 7.2. Can you compare the line 73 of the file phq_readin.f90 of your QE and phq_readin2.f90?

<img width="1005" alt="Screenshot 2023-09-06 at 6 10 28" src="https://github.com/nguyen-group/QERaman/assets/46996256/1120cb2e-5d29-4dee-9ff5-21e1609944b4">

**Comment by Mohiis** [comment]
Hi,
I was using QE 7.0. Changing to QE 7.2 solved the problem. Thank you
